export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESSFUL = "PRODUCT_LIST_SUCCESSFUL";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";  

export const PRODUCT_SAVE_REQUEST = "PRODUCT_SAVE_REQUEST";
export const PRODUCT_SAVE_SUCCESSFUL = "PRODUCT_SAVE_SUCCESSFUL";
export const PRODUCT_SAVE_FAIL = "PRODUCT_SAVE_FAIL";  

export const PRODUCT_DETAILED_REQUEST = "PRODUCT_DETAILED_REQUEST";
export const PRODUCT_DETAILED_SUCCESSFUL = "PRODUCT_DETAILED_SUCCESSFUL";
export const PRODUCT_DETAILED_FAIL = "PRODUCT_DETAILED_FAIL";  

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESSFUL = "PRODUCT_DELETE_SUCCESSFUL";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";  