export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESSFUL = "PRODUCT_LIST_SUCCESSFUL";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";  

export const PRODUCT_DETAILED_REQUEST = "PRODUCT_DETAILED_REQUEST";
export const PRODUCT_DETAILED_SUCCESSFUL = "PRODUCT_DETAILED_SUCCESSFUL";
export const PRODUCT_DETAILED_FAIL = "PRODUCT_DETAILED_FAIL";  