export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESSFUL = "USER_SIGNIN_SUCCESSFUL";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESSFUL = "USER_REGISTER_SUCCESSFUL";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";