const data = {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      categories: "Shirt",
      image: "/images/tolu.jpg",
      price: 100,
      brand: "Sneh",
      rating: 5.0,
      numReviews: 20,
      inStock: 7,
    },
    {
      _id: "2",
      name: "Fit Shirt",
      categories: "Shirt",
      image: "/images/tolu.jpg",
      price: 100,
      brand: "Sneh",
      rating: 5.0,
      numReviews: 20,
      inStock: 5,
    },
    {
      _id: "3",
      name: "Slim pant",
      categories: "Pants",
      image: "/images/tolu.jpg",
      price: 80,
      brand: "Sneh",
      rating: 5.0,
      numReviews: 20,
      inStock: 9,
    },
    {
      _id: "4",
      name: "Fit Pant",
      categories: "Pants",
      image: "/images/tolu.jpg",
      price: 70,
      brand: "Sneh",
      rating: 5.0,
      numReviews: 20,
      inStock: 10,
    },
    {
      _id: "5",
      name: "Best Shirt",
      categories: "Shirt",
      image: "/images/tolu.jpg",
      price: 155,
      brand: "Sneh",
      rating: 5.0,
      numReviews: 20,
      inStock: 3,
    },
    {
      _id: "6",
      name: "Best Pant",
      categories: "Pants",
      image: "/images/tolu.jpg",
      price: 150,
      brand: "Sneh",
      rating: 5.0,
      numReviews: 20,
      inStock: 10
    },
  ],
};
export default data;
